{{- if .Values.api_configfile }}
apiVersion: v1
kind: Secret
type: opaque
metadata:
{{ include "xavki_api.header" . | indent 2}}
stringData:
  config.yaml: |-
  {{- .Values.api_configfile | toYaml | nindent 5 }}
{{- end }}
