
api_image: priximmo/helm-api:v1.0
api_port: 8000
api_resources: {}
api_ingress:
  enabled: true
  url: api.kub
api_replicas: 2
api_configfile:
  redis_host: "redis-api.default.svc.cluster.local"
  redis_password: "mypassword"
  app_port: 8000
  app_listen: "0.0.0.0"
redis.enabled: true
