{{- if eq .Values.redis_bck true }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.redis_PersistentVolumeClaim_Bck.name }}
  annotations:
    "helm.sh/hook": pre-upgrade,pre-rollback
    "helm.sh/hook-weight": "2"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
spec:
  storageClassName: {{ .Values.redis_storageClass_bck }}
  accessModes:
    - {{ .Values.redis_PersistentVolumeClaim_Bck.mode }}
  resources:
    requests:
      storage: {{ .Values.redis_PersistentVolumeClaim_Bck.size }}
{{- end }}
